namespace Gu.Inject.Analyzers.Tests.GuInj001AddAutoBindTests
{
    using Gu.Inject;
    using Gu.Inject.Tests.Types;

    public static class Sandbox
    {
    }

    // <auto-generated/>
    public static class ContainerExtensions
    {
        /// <summary>
        /// Adds generated bindings for the graph where <see cref="Foo"/> is root.
        /// This method is generated by Gu.Inject.Analyzers.
        /// </summary>
        /// <param name="container">The <see cref="Inject.Container{Foo}"/>.</param>
        // a
        public static Container<Foo> AutoBind(this Container<Foo> container)
        {
            if (container == null)
            {
                throw new System.ArgumentNullException(nameof(container));
            }

            return container.Bind(x => new Foo(x.Get<Bar>()))
                            .Bind(_ => new Bar());
        }
    }
}
